language: generic
sudo: required

deploy:
  provider: snap
  edge:
    source: kyrofa/dpl
    branch: feature/snap-support
  on:
    branch: master # or all_branches: true
  token: 'this-is-a-test-token'
