language: generic
sudo: required

after_success:
- sudo apt update && sudo apt install -y snapd
- sudo snap install core
- sudo snap install snapcraft --classic

- /snap/bin/snapcraft

deploy:
  provider: snap
  edge:
    source: kyrofa/dpl
    branch: feature/snap-support
  on:
    branch: master # or all_branches: true
  channel: edge
  skip_cleanup: true
